using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

namespace NgLogViewer
{
    partial class MainForm
    {
        private IContainer components = null;

        private TabControl mainTabs;
        private TabPage queryPage;
        private TabPage settingPage;
        private TabPage statisticsPage;
        private Panel statisticsHost;
        private TableLayoutPanel queryRoot;
        private TableLayoutPanel topFilters;
        private Label startLabel;
        private Label endLabel;
        private Label categoryLabel;
        private Label jigLabel;
        private Label keywordLabel;
        private Label codeLabel;
        private Label logTypeLabel;
        private FlowLayoutPanel startDateTimePanel;
        private FlowLayoutPanel endDateTimePanel;
        private DateTimePicker startDatePicker;
        private DateTimePicker startTimePicker;
        private DateTimePicker endDatePicker;
        private DateTimePicker endTimePicker;
        private ComboBox categoryBox;
        private ComboBox jigBox;
        private TextBox keywordBox;
        private TextBox codeBox;
        private FlowLayoutPanel logLevelsPanel;
        private CheckBox infoCheck;
        private CheckBox errorCheck;
        private CheckBox debugCheck;
        private FlowLayoutPanel queryButtonsPanel;
        private Button queryButton;
        private Button cancelButton;
        private Button continueButton;
        private Button clearButton;
        private Button copyButton;
        private Button exportButton;
        private Button openLogsButton;
        private CheckBox liveCheck;
        private Label summaryLabel;
        private Panel gridHost;
        private DataGridView grid;
        private DataGridViewTextBoxColumn timeColumn;
        private DataGridViewTextBoxColumn levelColumn;
        private DataGridViewTextBoxColumn categoryColumn;
        private DataGridViewTextBoxColumn productionModeColumn;
        private DataGridViewTextBoxColumn jigColumn;
        private DataGridViewTextBoxColumn bottomCodeColumn;
        private DataGridViewTextBoxColumn topCodeColumn;
        private DataGridViewTextBoxColumn mainBoardCodeColumn;
        private DataGridViewTextBoxColumn reasonColumn;
        private DataGridViewTextBoxColumn contextColumn;
        private DataGridViewTextBoxColumn sourceDisplayNameColumn;
        private DataGridViewButtonColumn openSourceColumn;
        private ContextMenuStrip gridContextMenu;
        private ToolStripMenuItem copyCurrentCellMenuItem;
        private ToolStripMenuItem copySelectedRowsMenuItem;
        private ToolStripSeparator copyMenuSeparator;
        private ToolStripMenuItem copyReasonMenuItem;
        private ToolStripMenuItem copyMainBoardMenuItem;
        private ToolStripSeparator sourceMenuSeparator;
        private ToolStripMenuItem openSourceMenuItem;
        private ToolStripMenuItem locateSourceMenuItem;
        private Label statusLabel;
        private TableLayoutPanel settingsPanel;
        private Label pathLabel;
        private Label keywordsLabel;
        private Label refreshLabel;
        private Label maxLabel;
        private Label cleanupLabel;
        private TextBox pathBox;
        private TextBox customKeywordsBox;
        private FlowLayoutPanel folderButtonsPanel;
        private Button browseButton;
        private Button openSettingsFolderButton;
        private NumericUpDown refreshNumber;
        private NumericUpDown maxNumber;
        private NumericUpDown cleanupNumber;
        private Label refreshHelpLabel;
        private Label maxHelpLabel;
        private Label cleanupHelpLabel;
        private FlowLayoutPanel settingsButtonsPanel;
        private Button saveSettingsButton;
        private Button cleanupButton;
        private Label warningLabel;
        private Label referenceNoticeLabel;
        private Timer liveTimer;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.components = new Container();
            DataGridViewCellStyle headerStyle = new DataGridViewCellStyle();
            DataGridViewCellStyle rowStyle = new DataGridViewCellStyle();
            DataGridViewCellStyle alternateRowStyle = new DataGridViewCellStyle();
            DataGridViewCellStyle openButtonStyle = new DataGridViewCellStyle();
            this.mainTabs = new TabControl();
            this.queryPage = new TabPage();
            this.settingPage = new TabPage();
            this.statisticsPage = new TabPage();
            this.statisticsHost = new Panel();
            this.queryRoot = new TableLayoutPanel();
            this.topFilters = new TableLayoutPanel();
            this.startLabel = new Label();
            this.endLabel = new Label();
            this.categoryLabel = new Label();
            this.jigLabel = new Label();
            this.keywordLabel = new Label();
            this.codeLabel = new Label();
            this.logTypeLabel = new Label();
            this.startDateTimePanel = new FlowLayoutPanel();
            this.endDateTimePanel = new FlowLayoutPanel();
            this.startDatePicker = new DateTimePicker();
            this.startTimePicker = new DateTimePicker();
            this.endDatePicker = new DateTimePicker();
            this.endTimePicker = new DateTimePicker();
            this.categoryBox = new ComboBox();
            this.jigBox = new ComboBox();
            this.keywordBox = new TextBox();
            this.codeBox = new TextBox();
            this.logLevelsPanel = new FlowLayoutPanel();
            this.infoCheck = new CheckBox();
            this.errorCheck = new CheckBox();
            this.debugCheck = new CheckBox();
            this.queryButtonsPanel = new FlowLayoutPanel();
            this.queryButton = new Button();
            this.cancelButton = new Button();
            this.continueButton = new Button();
            this.clearButton = new Button();
            this.copyButton = new Button();
            this.exportButton = new Button();
            this.openLogsButton = new Button();
            this.liveCheck = new CheckBox();
            this.summaryLabel = new Label();
            this.gridHost = new Panel();
            this.grid = new DataGridView();
            this.timeColumn = new DataGridViewTextBoxColumn();
            this.levelColumn = new DataGridViewTextBoxColumn();
            this.categoryColumn = new DataGridViewTextBoxColumn();
            this.productionModeColumn = new DataGridViewTextBoxColumn();
            this.jigColumn = new DataGridViewTextBoxColumn();
            this.bottomCodeColumn = new DataGridViewTextBoxColumn();
            this.topCodeColumn = new DataGridViewTextBoxColumn();
            this.mainBoardCodeColumn = new DataGridViewTextBoxColumn();
            this.reasonColumn = new DataGridViewTextBoxColumn();
            this.contextColumn = new DataGridViewTextBoxColumn();
            this.sourceDisplayNameColumn = new DataGridViewTextBoxColumn();
            this.openSourceColumn = new DataGridViewButtonColumn();
            this.gridContextMenu = new ContextMenuStrip(this.components);
            this.copyCurrentCellMenuItem = new ToolStripMenuItem();
            this.copySelectedRowsMenuItem = new ToolStripMenuItem();
            this.copyMenuSeparator = new ToolStripSeparator();
            this.copyReasonMenuItem = new ToolStripMenuItem();
            this.copyMainBoardMenuItem = new ToolStripMenuItem();
            this.sourceMenuSeparator = new ToolStripSeparator();
            this.openSourceMenuItem = new ToolStripMenuItem();
            this.locateSourceMenuItem = new ToolStripMenuItem();
            this.statusLabel = new Label();
            this.settingsPanel = new TableLayoutPanel();
            this.pathLabel = new Label();
            this.keywordsLabel = new Label();
            this.refreshLabel = new Label();
            this.maxLabel = new Label();
            this.cleanupLabel = new Label();
            this.pathBox = new TextBox();
            this.customKeywordsBox = new TextBox();
            this.folderButtonsPanel = new FlowLayoutPanel();
            this.browseButton = new Button();
            this.openSettingsFolderButton = new Button();
            this.refreshNumber = new NumericUpDown();
            this.maxNumber = new NumericUpDown();
            this.cleanupNumber = new NumericUpDown();
            this.refreshHelpLabel = new Label();
            this.maxHelpLabel = new Label();
            this.cleanupHelpLabel = new Label();
            this.settingsButtonsPanel = new FlowLayoutPanel();
            this.saveSettingsButton = new Button();
            this.cleanupButton = new Button();
            this.warningLabel = new Label();
            this.referenceNoticeLabel = new Label();
            this.liveTimer = new Timer(this.components);
            this.mainTabs.SuspendLayout();
            this.queryPage.SuspendLayout();
            this.settingPage.SuspendLayout();
            this.queryRoot.SuspendLayout();
            this.topFilters.SuspendLayout();
            this.startDateTimePanel.SuspendLayout();
            this.endDateTimePanel.SuspendLayout();
            this.logLevelsPanel.SuspendLayout();
            this.queryButtonsPanel.SuspendLayout();
            this.gridHost.SuspendLayout();
            ((ISupportInitialize)(this.grid)).BeginInit();
            this.gridContextMenu.SuspendLayout();
            this.settingsPanel.SuspendLayout();
            this.folderButtonsPanel.SuspendLayout();
            ((ISupportInitialize)(this.refreshNumber)).BeginInit();
            ((ISupportInitialize)(this.maxNumber)).BeginInit();
            ((ISupportInitialize)(this.cleanupNumber)).BeginInit();
            this.settingsButtonsPanel.SuspendLayout();
            this.SuspendLayout();

            // mainTabs
            this.mainTabs.Controls.Add(this.queryPage);
            this.mainTabs.Controls.Add(this.statisticsPage);
            this.mainTabs.Controls.Add(this.settingPage);
            this.mainTabs.Dock = DockStyle.Fill;
            this.mainTabs.ItemSize = new Size(180, 34);
            this.mainTabs.Location = new Point(0, 0);
            this.mainTabs.Name = "mainTabs";
            this.mainTabs.Padding = new Point(18, 6);
            this.mainTabs.SelectedIndex = 0;
            this.mainTabs.Size = new Size(1484, 861);
            this.mainTabs.SizeMode = TabSizeMode.Fixed;

            // queryPage
            this.queryPage.BackColor = Color.FromArgb(242, 246, 250);
            this.queryPage.AutoScroll = true;
            this.queryPage.Controls.Add(this.queryRoot);
            this.queryPage.Location = new Point(4, 38);
            this.queryPage.Name = "queryPage";
            this.queryPage.Padding = new Padding(6);
            this.queryPage.Size = new Size(1476, 819);
            this.queryPage.Text = "NG 查询与实时监控";

            // statisticsPage
            this.statisticsPage.BackColor = Color.FromArgb(242, 246, 250);
            this.statisticsPage.AutoScroll = true;
            this.statisticsPage.Controls.Add(this.statisticsHost);
            this.statisticsPage.Location = new Point(4, 38);
            this.statisticsPage.Name = "statisticsPage";
            this.statisticsPage.Padding = new Padding(6);
            this.statisticsPage.Size = new Size(1476, 819);
            this.statisticsPage.Text = "焊接统计";
            this.statisticsHost.Dock = DockStyle.Fill;
            this.statisticsHost.Name = "statisticsHost";

            // settingPage
            this.settingPage.BackColor = Color.FromArgb(242, 246, 250);
            this.settingPage.AutoScroll = true;
            this.settingPage.Controls.Add(this.settingsPanel);
            this.settingPage.Location = new Point(4, 38);
            this.settingPage.Name = "settingPage";
            this.settingPage.Padding = new Padding(6);
            this.settingPage.Size = new Size(1476, 819);
            this.settingPage.Text = "设置与安全清理";

            // queryRoot
            this.queryRoot.ColumnCount = 1;
            this.queryRoot.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            this.queryRoot.Controls.Add(this.topFilters, 0, 0);
            this.queryRoot.Controls.Add(this.gridHost, 0, 1);
            this.queryRoot.Controls.Add(this.statusLabel, 0, 2);
            this.queryRoot.Dock = DockStyle.Fill;
            this.queryRoot.Location = new Point(6, 6);
            this.queryRoot.Name = "queryRoot";
            this.queryRoot.RowCount = 3;
            this.queryRoot.RowStyles.Add(new RowStyle(SizeType.Absolute, 196F));
            this.queryRoot.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            this.queryRoot.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
            this.queryRoot.Size = new Size(1464, 807);

            // topFilters
            this.topFilters.BackColor = Color.White;
            this.topFilters.ColumnCount = 8;
            this.topFilters.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize));
            this.topFilters.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 25F));
            this.topFilters.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize));
            this.topFilters.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 25F));
            this.topFilters.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize));
            this.topFilters.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 25F));
            this.topFilters.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize));
            this.topFilters.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 25F));
            this.topFilters.Controls.Add(this.startLabel, 0, 0);
            this.topFilters.Controls.Add(this.startDateTimePanel, 1, 0);
            this.topFilters.Controls.Add(this.endLabel, 2, 0);
            this.topFilters.Controls.Add(this.endDateTimePanel, 3, 0);
            this.topFilters.Controls.Add(this.categoryLabel, 4, 0);
            this.topFilters.Controls.Add(this.categoryBox, 5, 0);
            this.topFilters.Controls.Add(this.jigLabel, 6, 0);
            this.topFilters.Controls.Add(this.jigBox, 7, 0);
            this.topFilters.Controls.Add(this.keywordLabel, 0, 1);
            this.topFilters.Controls.Add(this.keywordBox, 1, 1);
            this.topFilters.Controls.Add(this.codeLabel, 2, 1);
            this.topFilters.Controls.Add(this.codeBox, 3, 1);
            this.topFilters.Controls.Add(this.logTypeLabel, 4, 1);
            this.topFilters.Controls.Add(this.logLevelsPanel, 5, 1);
            this.topFilters.Controls.Add(this.queryButtonsPanel, 0, 2);
            this.topFilters.Controls.Add(this.summaryLabel, 0, 3);
            this.topFilters.Dock = DockStyle.Fill;
            this.topFilters.Location = new Point(6, 6);
            this.topFilters.Margin = new Padding(6);
            this.topFilters.Name = "topFilters";
            this.topFilters.Padding = new Padding(16, 12, 16, 8);
            this.topFilters.RowCount = 4;
            this.topFilters.RowStyles.Add(new RowStyle(SizeType.Absolute, 42F));
            this.topFilters.RowStyles.Add(new RowStyle(SizeType.Absolute, 42F));
            this.topFilters.RowStyles.Add(new RowStyle(SizeType.Absolute, 54F));
            this.topFilters.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
            this.topFilters.SetColumnSpan(this.logLevelsPanel, 3);
            this.topFilters.SetColumnSpan(this.queryButtonsPanel, 8);
            this.topFilters.SetColumnSpan(this.summaryLabel, 8);

            // filter labels
            this.startLabel.Anchor = AnchorStyles.Left;
            this.startLabel.AutoSize = true;
            this.startLabel.Font = new Font("Microsoft YaHei UI", 9F, FontStyle.Bold);
            this.startLabel.Text = "开始时间";
            this.endLabel.Anchor = AnchorStyles.Left;
            this.endLabel.AutoSize = true;
            this.endLabel.Font = new Font("Microsoft YaHei UI", 9F, FontStyle.Bold);
            this.endLabel.Text = "结束时间";
            this.categoryLabel.Anchor = AnchorStyles.Left;
            this.categoryLabel.AutoSize = true;
            this.categoryLabel.Font = new Font("Microsoft YaHei UI", 9F, FontStyle.Bold);
            this.categoryLabel.Text = "NG分类";
            this.jigLabel.Anchor = AnchorStyles.Left;
            this.jigLabel.AutoSize = true;
            this.jigLabel.Font = new Font("Microsoft YaHei UI", 9F, FontStyle.Bold);
            this.jigLabel.Text = "治具";
            this.keywordLabel.Anchor = AnchorStyles.Left;
            this.keywordLabel.AutoSize = true;
            this.keywordLabel.Font = new Font("Microsoft YaHei UI", 9F, FontStyle.Bold);
            this.keywordLabel.Text = "原因关键字";
            this.codeLabel.Anchor = AnchorStyles.Left;
            this.codeLabel.AutoSize = true;
            this.codeLabel.Font = new Font("Microsoft YaHei UI", 9F, FontStyle.Bold);
            this.codeLabel.Text = "任意条码";
            this.logTypeLabel.Anchor = AnchorStyles.Left;
            this.logTypeLabel.AutoSize = true;
            this.logTypeLabel.Font = new Font("Microsoft YaHei UI", 9F, FontStyle.Bold);
            this.logTypeLabel.Text = "日志类型";

            // date/time panels and pickers
            this.startDateTimePanel.AutoSize = true;
            this.startDateTimePanel.Controls.Add(this.startDatePicker);
            this.startDateTimePanel.Controls.Add(this.startTimePicker);
            this.startDateTimePanel.Dock = DockStyle.Fill;
            this.startDateTimePanel.WrapContents = false;
            this.endDateTimePanel.AutoSize = true;
            this.endDateTimePanel.Controls.Add(this.endDatePicker);
            this.endDateTimePanel.Controls.Add(this.endTimePicker);
            this.endDateTimePanel.Dock = DockStyle.Fill;
            this.endDateTimePanel.WrapContents = false;
            this.startDatePicker.CustomFormat = "yyyy-MM-dd";
            this.startDatePicker.Format = DateTimePickerFormat.Custom;
            this.startDatePicker.Width = 125;
            this.startTimePicker.CustomFormat = "HH:mm:ss";
            this.startTimePicker.Format = DateTimePickerFormat.Custom;
            this.startTimePicker.ShowUpDown = true;
            this.startTimePicker.Width = 92;
            this.endDatePicker.CustomFormat = "yyyy-MM-dd";
            this.endDatePicker.Format = DateTimePickerFormat.Custom;
            this.endDatePicker.Width = 125;
            this.endTimePicker.CustomFormat = "HH:mm:ss";
            this.endTimePicker.Format = DateTimePickerFormat.Custom;
            this.endTimePicker.ShowUpDown = true;
            this.endTimePicker.Width = 92;

            // filter inputs
            this.categoryBox.Dock = DockStyle.Fill;
            this.categoryBox.DropDownStyle = ComboBoxStyle.DropDownList;
            this.categoryBox.Items.AddRange(new object[] { "全部", "工站/接口", "底板/导向板比对", "焊接/MES", "扫码异常", "设备/通信", "系统异常", "其他NG" });
            this.categoryBox.SelectedIndex = 0;
            this.jigBox.Dock = DockStyle.Fill;
            this.jigBox.DropDownStyle = ComboBoxStyle.DropDownList;
            this.jigBox.Items.AddRange(new object[] { "全部", "治具1", "治具2" });
            this.jigBox.SelectedIndex = 0;
            this.keywordBox.Dock = DockStyle.Fill;
            this.keywordBox.Margin = new Padding(3, 7, 10, 3);
            this.codeBox.Dock = DockStyle.Fill;
            this.codeBox.Margin = new Padding(3, 7, 10, 3);

            // logLevelsPanel
            this.logLevelsPanel.AutoSize = true;
            this.logLevelsPanel.Controls.Add(this.infoCheck);
            this.logLevelsPanel.Controls.Add(this.errorCheck);
            this.logLevelsPanel.Controls.Add(this.debugCheck);
            this.logLevelsPanel.Dock = DockStyle.Fill;
            this.logLevelsPanel.Padding = new Padding(0, 4, 0, 0);
            this.logLevelsPanel.WrapContents = false;
            this.infoCheck.AutoSize = true;
            this.infoCheck.Checked = true;
            this.infoCheck.CheckState = CheckState.Checked;
            this.infoCheck.Text = "信息/WARN";
            this.errorCheck.AutoSize = true;
            this.errorCheck.Checked = true;
            this.errorCheck.CheckState = CheckState.Checked;
            this.errorCheck.Text = "ERROR";
            this.debugCheck.AutoSize = true;
            this.debugCheck.Text = "DEBUG（较慢）";

            // queryButtonsPanel
            this.queryButtonsPanel.AutoSize = true;
            this.queryButtonsPanel.Controls.Add(this.queryButton);
            this.queryButtonsPanel.Controls.Add(this.cancelButton);
            this.queryButtonsPanel.Controls.Add(this.continueButton);
            this.queryButtonsPanel.Controls.Add(this.clearButton);
            this.queryButtonsPanel.Controls.Add(this.copyButton);
            this.queryButtonsPanel.Controls.Add(this.exportButton);
            this.queryButtonsPanel.Controls.Add(this.openLogsButton);
            this.queryButtonsPanel.Controls.Add(this.liveCheck);
            this.queryButtonsPanel.Dock = DockStyle.Fill;
            this.queryButtonsPanel.Padding = new Padding(0, 5, 0, 0);
            this.queryButtonsPanel.WrapContents = false;

            // query buttons
            this.queryButton.AutoSize = true;
            this.queryButton.BackColor = Color.FromArgb(25, 91, 155);
            this.queryButton.Cursor = Cursors.Hand;
            this.queryButton.FlatAppearance.BorderSize = 0;
            this.queryButton.FlatStyle = FlatStyle.Flat;
            this.queryButton.ForeColor = Color.White;
            this.queryButton.Padding = new Padding(12, 2, 12, 2);
            this.queryButton.Text = "开始查询";
            this.queryButton.UseVisualStyleBackColor = false;
            this.queryButton.Click += new System.EventHandler(this.QueryButton_Click);
            this.cancelButton.AutoSize = true;
            this.cancelButton.BackColor = Color.FromArgb(108, 117, 125);
            this.cancelButton.Cursor = Cursors.Hand;
            this.cancelButton.Enabled = false;
            this.cancelButton.FlatAppearance.BorderSize = 0;
            this.cancelButton.FlatStyle = FlatStyle.Flat;
            this.cancelButton.ForeColor = Color.White;
            this.cancelButton.Padding = new Padding(12, 2, 12, 2);
            this.cancelButton.Text = "中止查询";
            this.cancelButton.UseVisualStyleBackColor = false;
            this.cancelButton.Click += new System.EventHandler(this.CancelButton_Click);
            this.continueButton.AutoSize = true;
            this.continueButton.BackColor = Color.FromArgb(34, 139, 94);
            this.continueButton.Cursor = Cursors.Hand;
            this.continueButton.Enabled = false;
            this.continueButton.FlatAppearance.BorderSize = 0;
            this.continueButton.FlatStyle = FlatStyle.Flat;
            this.continueButton.ForeColor = Color.White;
            this.continueButton.Padding = new Padding(12, 2, 12, 2);
            this.continueButton.Text = "继续剩余";
            this.continueButton.UseVisualStyleBackColor = false;
            this.continueButton.Click += new System.EventHandler(this.ContinueButton_Click);
            this.clearButton.AutoSize = true;
            this.clearButton.BackColor = Color.FromArgb(197, 95, 38);
            this.clearButton.Cursor = Cursors.Hand;
            this.clearButton.FlatAppearance.BorderSize = 0;
            this.clearButton.FlatStyle = FlatStyle.Flat;
            this.clearButton.ForeColor = Color.White;
            this.clearButton.Padding = new Padding(12, 2, 12, 2);
            this.clearButton.Text = "清空显示";
            this.clearButton.UseVisualStyleBackColor = false;
            this.clearButton.Click += new System.EventHandler(this.ClearButton_Click);
            this.copyButton.AutoSize = true;
            this.copyButton.BackColor = Color.FromArgb(107, 76, 154);
            this.copyButton.Cursor = Cursors.Hand;
            this.copyButton.FlatAppearance.BorderSize = 0;
            this.copyButton.FlatStyle = FlatStyle.Flat;
            this.copyButton.ForeColor = Color.White;
            this.copyButton.Padding = new Padding(12, 2, 12, 2);
            this.copyButton.Text = "复制选中";
            this.copyButton.UseVisualStyleBackColor = false;
            this.copyButton.Click += new System.EventHandler(this.CopyButton_Click);
            this.exportButton.AutoSize = true;
            this.exportButton.BackColor = Color.FromArgb(26, 135, 84);
            this.exportButton.Cursor = Cursors.Hand;
            this.exportButton.FlatAppearance.BorderSize = 0;
            this.exportButton.FlatStyle = FlatStyle.Flat;
            this.exportButton.ForeColor = Color.White;
            this.exportButton.Padding = new Padding(12, 2, 12, 2);
            this.exportButton.Text = "导出 CSV";
            this.exportButton.UseVisualStyleBackColor = false;
            this.exportButton.Click += new System.EventHandler(this.ExportCsv);
            this.openLogsButton.AutoSize = true;
            this.openLogsButton.BackColor = Color.FromArgb(65, 105, 135);
            this.openLogsButton.Cursor = Cursors.Hand;
            this.openLogsButton.FlatAppearance.BorderSize = 0;
            this.openLogsButton.FlatStyle = FlatStyle.Flat;
            this.openLogsButton.ForeColor = Color.White;
            this.openLogsButton.Padding = new Padding(12, 2, 12, 2);
            this.openLogsButton.Text = "打开日志文件夹";
            this.openLogsButton.UseVisualStyleBackColor = false;
            this.openLogsButton.Click += new System.EventHandler(this.OpenLogsButton_Click);
            this.liveCheck.Anchor = AnchorStyles.Left;
            this.liveCheck.AutoSize = true;
            this.liveCheck.ForeColor = Color.FromArgb(177, 45, 45);
            this.liveCheck.Margin = new Padding(8, 8, 3, 3);
            this.liveCheck.Text = "实时监控新增 NG";
            this.liveCheck.CheckedChanged += new System.EventHandler(this.LiveChanged);

            // summaryLabel
            this.summaryLabel.Anchor = AnchorStyles.Left;
            this.summaryLabel.AutoSize = true;
            this.summaryLabel.Font = new Font("Microsoft YaHei UI", 9.5F, FontStyle.Bold);
            this.summaryLabel.ForeColor = Color.FromArgb(35, 63, 92);
            this.summaryLabel.Padding = new Padding(4, 5, 0, 0);
            this.summaryLabel.Text = "尚未查询";

            // gridHost
            this.gridHost.BackColor = Color.FromArgb(242, 246, 250);
            this.gridHost.Controls.Add(this.grid);
            this.gridHost.Dock = DockStyle.Fill;
            this.gridHost.Padding = new Padding(6, 10, 6, 8);

            // grid
            this.grid.AllowUserToAddRows = false;
            this.grid.AllowUserToDeleteRows = false;
            this.grid.AllowUserToOrderColumns = true;
            alternateRowStyle.BackColor = Color.FromArgb(247, 250, 253);
            alternateRowStyle.ForeColor = Color.FromArgb(190, 0, 0);
            alternateRowStyle.SelectionForeColor = Color.FromArgb(190, 0, 0);
            this.grid.AlternatingRowsDefaultCellStyle = alternateRowStyle;
            this.grid.AutoGenerateColumns = false;
            this.grid.AutoSizeRowsMode = DataGridViewAutoSizeRowsMode.None;
            this.grid.BackgroundColor = Color.White;
            this.grid.BorderStyle = BorderStyle.None;
            this.grid.CellBorderStyle = DataGridViewCellBorderStyle.SingleHorizontal;
            headerStyle.Alignment = DataGridViewContentAlignment.MiddleLeft;
            headerStyle.BackColor = Color.FromArgb(35, 63, 92);
            headerStyle.Font = new Font("Microsoft YaHei UI", 9F, FontStyle.Bold);
            headerStyle.ForeColor = Color.White;
            headerStyle.Padding = new Padding(5, 0, 0, 0);
            headerStyle.SelectionBackColor = Color.FromArgb(35, 63, 92);
            headerStyle.SelectionForeColor = Color.White;
            this.grid.ColumnHeadersDefaultCellStyle = headerStyle;
            this.grid.ColumnHeadersHeight = 38;
            this.grid.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
            this.grid.Columns.AddRange(new DataGridViewColumn[] {
                this.timeColumn, this.levelColumn, this.categoryColumn, this.productionModeColumn, this.jigColumn,
                this.bottomCodeColumn, this.topCodeColumn, this.mainBoardCodeColumn,
                this.reasonColumn, this.contextColumn, this.sourceDisplayNameColumn,
                this.openSourceColumn });
            this.grid.ContextMenuStrip = this.gridContextMenu;
            rowStyle.BackColor = Color.White;
            rowStyle.Font = new Font("Microsoft YaHei UI", 9F, FontStyle.Bold);
            rowStyle.ForeColor = Color.FromArgb(190, 0, 0);
            rowStyle.Padding = new Padding(5, 0, 5, 0);
            rowStyle.SelectionBackColor = Color.FromArgb(205, 225, 244);
            rowStyle.SelectionForeColor = Color.FromArgb(190, 0, 0);
            this.grid.DefaultCellStyle = rowStyle;
            this.grid.Dock = DockStyle.Fill;
            this.grid.EnableHeadersVisualStyles = false;
            this.grid.GridColor = Color.FromArgb(225, 231, 237);
            this.grid.MultiSelect = true;
            this.grid.ReadOnly = true;
            this.grid.RowHeadersVisible = false;
            this.grid.RowTemplate.Height = 30;
            this.grid.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            this.grid.ShowCellToolTips = true;
            this.grid.CellContentClick += new DataGridViewCellEventHandler(this.GridCellContentClick);
            this.grid.CellDoubleClick += new DataGridViewCellEventHandler(this.Grid_CellDoubleClick);
            this.grid.CellFormatting += new DataGridViewCellFormattingEventHandler(this.GridFormatting);
            this.grid.CellToolTipTextNeeded += new DataGridViewCellToolTipTextNeededEventHandler(this.GridCellToolTipTextNeeded);
            this.grid.ColumnHeaderMouseClick += new DataGridViewCellMouseEventHandler(this.GridColumnHeaderMouseClick);

            // grid columns
            this.timeColumn.DataPropertyName = "Time";
            this.timeColumn.DefaultCellStyle = new DataGridViewCellStyle { Format = "yyyy-MM-dd HH:mm:ss.ffff" };
            this.timeColumn.HeaderText = "时间（点击排序）";
            this.timeColumn.Name = "Time";
            this.timeColumn.ReadOnly = true;
            this.timeColumn.Width = 175;
            this.levelColumn.DataPropertyName = "Level";
            this.levelColumn.HeaderText = "级别";
            this.levelColumn.Name = "Level";
            this.levelColumn.ReadOnly = true;
            this.levelColumn.Width = 65;
            this.categoryColumn.DataPropertyName = "Category";
            this.categoryColumn.HeaderText = "NG分类";
            this.categoryColumn.Name = "Category";
            this.categoryColumn.ReadOnly = true;
            this.categoryColumn.Width = 125;
            this.productionModeColumn.DataPropertyName = "ProductionMode";
            this.productionModeColumn.HeaderText = "生产模式";
            this.productionModeColumn.Name = "ProductionMode";
            this.productionModeColumn.ReadOnly = true;
            this.productionModeColumn.Width = 85;
            this.jigColumn.DataPropertyName = "Jig";
            this.jigColumn.HeaderText = "治具";
            this.jigColumn.Name = "Jig";
            this.jigColumn.ReadOnly = true;
            this.jigColumn.Width = 58;
            this.bottomCodeColumn.DataPropertyName = "BottomCode";
            this.bottomCodeColumn.HeaderText = "底板码";
            this.bottomCodeColumn.Name = "BottomCode";
            this.bottomCodeColumn.ReadOnly = true;
            this.bottomCodeColumn.Width = 155;
            this.topCodeColumn.DataPropertyName = "TopCode";
            this.topCodeColumn.HeaderText = "导向板码";
            this.topCodeColumn.Name = "TopCode";
            this.topCodeColumn.ReadOnly = true;
            this.topCodeColumn.Width = 155;
            this.mainBoardCodeColumn.DataPropertyName = "MainBoardCode";
            this.mainBoardCodeColumn.HeaderText = "主板码";
            this.mainBoardCodeColumn.Name = "MainBoardCode";
            this.mainBoardCodeColumn.ReadOnly = true;
            this.mainBoardCodeColumn.Width = 210;
            this.reasonColumn.DataPropertyName = "Reason";
            this.reasonColumn.HeaderText = "NG原因";
            this.reasonColumn.Name = "Reason";
            this.reasonColumn.ReadOnly = true;
            this.reasonColumn.Width = 410;
            this.contextColumn.DataPropertyName = "Context";
            this.contextColumn.HeaderText = "关联上下文";
            this.contextColumn.Name = "Context";
            this.contextColumn.ReadOnly = true;
            this.contextColumn.Width = 330;
            this.sourceDisplayNameColumn.DataPropertyName = "SourceDisplayName";
            this.sourceDisplayNameColumn.HeaderText = "来源文件";
            this.sourceDisplayNameColumn.Name = "SourceDisplayName";
            this.sourceDisplayNameColumn.ReadOnly = true;
            this.sourceDisplayNameColumn.Width = 225;
            openButtonStyle.BackColor = Color.FromArgb(232, 241, 249);
            openButtonStyle.ForeColor = Color.FromArgb(25, 91, 155);
            openButtonStyle.SelectionBackColor = Color.FromArgb(193, 218, 240);
            this.openSourceColumn.DefaultCellStyle = openButtonStyle;
            this.openSourceColumn.FlatStyle = FlatStyle.Flat;
            this.openSourceColumn.HeaderText = "原文件";
            this.openSourceColumn.Name = "OpenSourceAction";
            this.openSourceColumn.ReadOnly = true;
            this.openSourceColumn.SortMode = DataGridViewColumnSortMode.NotSortable;
            this.openSourceColumn.Text = "打开";
            this.openSourceColumn.UseColumnTextForButtonValue = true;
            this.openSourceColumn.Width = 64;

            // gridContextMenu
            this.gridContextMenu.Items.AddRange(new ToolStripItem[] {
                this.copyCurrentCellMenuItem, this.copySelectedRowsMenuItem, this.copyMenuSeparator,
                this.copyReasonMenuItem, this.copyMainBoardMenuItem, this.sourceMenuSeparator,
                this.openSourceMenuItem, this.locateSourceMenuItem });
            this.copyCurrentCellMenuItem.Text = "复制当前单元格";
            this.copyCurrentCellMenuItem.Click += new System.EventHandler(this.CopyCurrentCellMenuItem_Click);
            this.copySelectedRowsMenuItem.Text = "复制选中行（含完整信息）";
            this.copySelectedRowsMenuItem.Click += new System.EventHandler(this.CopySelectedRowsMenuItem_Click);
            this.copyReasonMenuItem.Text = "复制 NG 原因";
            this.copyReasonMenuItem.Click += new System.EventHandler(this.CopyReasonMenuItem_Click);
            this.copyMainBoardMenuItem.Text = "复制主板码";
            this.copyMainBoardMenuItem.Click += new System.EventHandler(this.CopyMainBoardMenuItem_Click);
            this.openSourceMenuItem.Text = "打开来源日志";
            this.openSourceMenuItem.Click += new System.EventHandler(this.OpenSourceMenuItem_Click);
            this.locateSourceMenuItem.Text = "在文件夹中定位来源日志";
            this.locateSourceMenuItem.Click += new System.EventHandler(this.LocateSourceMenuItem_Click);

            // statusLabel
            this.statusLabel.BackColor = Color.FromArgb(225, 236, 246);
            this.statusLabel.Dock = DockStyle.Fill;
            this.statusLabel.ForeColor = Color.FromArgb(35, 63, 92);
            this.statusLabel.Padding = new Padding(14, 7, 0, 0);
            this.statusLabel.Text = "只读安全模式：双击看详情；来源文件右侧可直接打开原日志。";

            // settingsPanel
            this.settingsPanel.BackColor = Color.White;
            this.settingsPanel.ColumnCount = 3;
            this.settingsPanel.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize));
            this.settingsPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            this.settingsPanel.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize));
            this.settingsPanel.Controls.Add(this.pathLabel, 0, 0);
            this.settingsPanel.Controls.Add(this.pathBox, 1, 0);
            this.settingsPanel.Controls.Add(this.folderButtonsPanel, 2, 0);
            this.settingsPanel.Controls.Add(this.keywordsLabel, 0, 1);
            this.settingsPanel.Controls.Add(this.customKeywordsBox, 1, 1);
            this.settingsPanel.Controls.Add(this.refreshLabel, 0, 2);
            this.settingsPanel.Controls.Add(this.refreshNumber, 1, 2);
            this.settingsPanel.Controls.Add(this.refreshHelpLabel, 2, 2);
            this.settingsPanel.Controls.Add(this.maxLabel, 0, 3);
            this.settingsPanel.Controls.Add(this.maxNumber, 1, 3);
            this.settingsPanel.Controls.Add(this.maxHelpLabel, 2, 3);
            this.settingsPanel.Controls.Add(this.cleanupLabel, 0, 4);
            this.settingsPanel.Controls.Add(this.cleanupNumber, 1, 4);
            this.settingsPanel.Controls.Add(this.cleanupHelpLabel, 2, 4);
            this.settingsPanel.Controls.Add(this.settingsButtonsPanel, 1, 5);
            this.settingsPanel.Controls.Add(this.referenceNoticeLabel, 0, 6);
            this.settingsPanel.Controls.Add(this.warningLabel, 0, 7);
            this.settingsPanel.Dock = DockStyle.Top;
            this.settingsPanel.Height = 390;
            this.settingsPanel.Margin = new Padding(8);
            this.settingsPanel.Name = "settingsPanel";
            this.settingsPanel.Padding = new Padding(26, 24, 26, 20);
            this.settingsPanel.RowCount = 8;
            this.settingsPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 46F));
            this.settingsPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 46F));
            this.settingsPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 46F));
            this.settingsPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 46F));
            this.settingsPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 46F));
            this.settingsPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 58F));
            this.settingsPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 48F));
            this.settingsPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            this.settingsPanel.SetColumnSpan(this.customKeywordsBox, 2);
            this.settingsPanel.SetColumnSpan(this.settingsButtonsPanel, 2);
            this.settingsPanel.SetColumnSpan(this.warningLabel, 3);
            this.settingsPanel.SetColumnSpan(this.referenceNoticeLabel, 3);

            // settings labels and inputs
            this.pathLabel.Anchor = AnchorStyles.Left;
            this.pathLabel.AutoSize = true;
            this.pathLabel.Font = new Font("Microsoft YaHei UI", 9F, FontStyle.Bold);
            this.pathLabel.Text = "日志目录";
            this.keywordsLabel.Anchor = AnchorStyles.Left;
            this.keywordsLabel.AutoSize = true;
            this.keywordsLabel.Font = new Font("Microsoft YaHei UI", 9F, FontStyle.Bold);
            this.keywordsLabel.Text = "NG识别关键词";
            this.refreshLabel.Anchor = AnchorStyles.Left;
            this.refreshLabel.AutoSize = true;
            this.refreshLabel.Font = new Font("Microsoft YaHei UI", 9F, FontStyle.Bold);
            this.refreshLabel.Text = "实时刷新秒数";
            this.maxLabel.Anchor = AnchorStyles.Left;
            this.maxLabel.AutoSize = true;
            this.maxLabel.Font = new Font("Microsoft YaHei UI", 9F, FontStyle.Bold);
            this.maxLabel.Text = "界面最多显示";
            this.cleanupLabel.Anchor = AnchorStyles.Left;
            this.cleanupLabel.AutoSize = true;
            this.cleanupLabel.Font = new Font("Microsoft YaHei UI", 9F, FontStyle.Bold);
            this.cleanupLabel.Text = "历史清理天数";
            this.pathBox.Dock = DockStyle.Fill;
            this.pathBox.Margin = new Padding(3, 7, 8, 3);
            this.customKeywordsBox.Dock = DockStyle.Fill;
            this.customKeywordsBox.Margin = new Padding(3, 7, 3, 3);

            // folderButtonsPanel
            this.folderButtonsPanel.AutoSize = true;
            this.folderButtonsPanel.Controls.Add(this.browseButton);
            this.folderButtonsPanel.Controls.Add(this.openSettingsFolderButton);
            this.folderButtonsPanel.Dock = DockStyle.Fill;
            this.folderButtonsPanel.WrapContents = false;
            this.browseButton.AutoSize = true;
            this.browseButton.BackColor = Color.FromArgb(25, 91, 155);
            this.browseButton.FlatAppearance.BorderSize = 0;
            this.browseButton.FlatStyle = FlatStyle.Flat;
            this.browseButton.ForeColor = Color.White;
            this.browseButton.Padding = new Padding(12, 2, 12, 2);
            this.browseButton.Text = "选择目录";
            this.browseButton.UseVisualStyleBackColor = false;
            this.browseButton.Click += new System.EventHandler(this.BrowseFolder);
            this.openSettingsFolderButton.AutoSize = true;
            this.openSettingsFolderButton.BackColor = Color.FromArgb(65, 105, 135);
            this.openSettingsFolderButton.FlatAppearance.BorderSize = 0;
            this.openSettingsFolderButton.FlatStyle = FlatStyle.Flat;
            this.openSettingsFolderButton.ForeColor = Color.White;
            this.openSettingsFolderButton.Padding = new Padding(12, 2, 12, 2);
            this.openSettingsFolderButton.Text = "打开目录";
            this.openSettingsFolderButton.UseVisualStyleBackColor = false;
            this.openSettingsFolderButton.Click += new System.EventHandler(this.OpenSettingsFolderButton_Click);

            // setting values/help
            this.refreshNumber.Anchor = AnchorStyles.Left;
            this.refreshNumber.Minimum = 3;
            this.refreshNumber.Maximum = 60;
            this.refreshNumber.Value = 5;
            this.refreshNumber.Width = 160;
            this.maxNumber.Anchor = AnchorStyles.Left;
            this.maxNumber.Minimum = 100;
            this.maxNumber.Maximum = 20000;
            this.maxNumber.Value = 3000;
            this.maxNumber.Width = 160;
            this.cleanupNumber.Anchor = AnchorStyles.Left;
            this.cleanupNumber.Minimum = 7;
            this.cleanupNumber.Maximum = 3650;
            this.cleanupNumber.Value = 90;
            this.cleanupNumber.Width = 160;
            this.refreshHelpLabel.Anchor = AnchorStyles.Left;
            this.refreshHelpLabel.AutoSize = true;
            this.refreshHelpLabel.ForeColor = Color.DimGray;
            this.refreshHelpLabel.Text = "建议 5 秒以上，只增量读取新增日志";
            this.maxHelpLabel.Anchor = AnchorStyles.Left;
            this.maxHelpLabel.AutoSize = true;
            this.maxHelpLabel.ForeColor = Color.DimGray;
            this.maxHelpLabel.Text = "建议 3000 条，防止界面卡顿";
            this.cleanupHelpLabel.Anchor = AnchorStyles.Left;
            this.cleanupHelpLabel.AutoSize = true;
            this.cleanupHelpLabel.ForeColor = Color.DimGray;
            this.cleanupHelpLabel.Text = "只删除早于该天数的日志，永不删除今天文件";

            // settingsButtonsPanel
            this.settingsButtonsPanel.AutoSize = true;
            this.settingsButtonsPanel.Controls.Add(this.saveSettingsButton);
            this.settingsButtonsPanel.Controls.Add(this.cleanupButton);
            this.settingsButtonsPanel.Dock = DockStyle.Fill;
            this.saveSettingsButton.AutoSize = true;
            this.saveSettingsButton.BackColor = Color.FromArgb(20, 130, 80);
            this.saveSettingsButton.FlatAppearance.BorderSize = 0;
            this.saveSettingsButton.FlatStyle = FlatStyle.Flat;
            this.saveSettingsButton.ForeColor = Color.White;
            this.saveSettingsButton.Padding = new Padding(12, 2, 12, 2);
            this.saveSettingsButton.Text = "保存设置";
            this.saveSettingsButton.UseVisualStyleBackColor = false;
            this.saveSettingsButton.Click += new System.EventHandler(this.SaveSettings);
            this.cleanupButton.AutoSize = true;
            this.cleanupButton.BackColor = Color.FromArgb(180, 50, 45);
            this.cleanupButton.FlatAppearance.BorderSize = 0;
            this.cleanupButton.FlatStyle = FlatStyle.Flat;
            this.cleanupButton.ForeColor = Color.White;
            this.cleanupButton.Padding = new Padding(12, 2, 12, 2);
            this.cleanupButton.Text = "删除过期历史日志";
            this.cleanupButton.UseVisualStyleBackColor = false;
            this.cleanupButton.Click += new System.EventHandler(this.CleanupOldLogs);
            this.warningLabel.AutoSize = true;
            this.warningLabel.ForeColor = Color.FromArgb(167, 45, 48);
            this.warningLabel.MaximumSize = new Size(1100, 0);
            this.warningLabel.Padding = new Padding(0, 16, 0, 0);
            this.warningLabel.Text = "目录说明：既可以选择包含 info、error、debug 的 logs 根目录，也可以直接选择其中一个子目录。\r\n安全说明：查询和实时监控始终只读；‘清空显示’不删文件。建议机台生产时不要执行磁盘清理。";
            this.referenceNoticeLabel.AutoSize = true;
            this.referenceNoticeLabel.BackColor = Color.FromArgb(255, 247, 225);
            this.referenceNoticeLabel.Dock = DockStyle.Fill;
            this.referenceNoticeLabel.Font = new Font("Microsoft YaHei UI", 10F, FontStyle.Bold);
            this.referenceNoticeLabel.ForeColor = Color.FromArgb(165, 85, 0);
            this.referenceNoticeLabel.Padding = new Padding(12, 12, 0, 0);
            this.referenceNoticeLabel.Text = "说明：该程序仅供参考，亟待完善。";

            // timer and form
            this.liveTimer.Tick += new System.EventHandler(this.LiveTick);
            this.AutoScaleDimensions = new SizeF(7F, 17F);
            this.AutoScaleMode = AutoScaleMode.Font;
            this.BackColor = Color.FromArgb(242, 246, 250);
            this.ClientSize = new Size(1484, 861);
            this.Controls.Add(this.mainTabs);
            this.Font = new Font("Microsoft YaHei UI", 9F);
            this.MinimumSize = new Size(650, 440);
            this.Name = "MainForm";
            this.StartPosition = FormStartPosition.CenterScreen;
            this.Text = "NG日志查询工具（只读优先）";
            this.FormClosing += new FormClosingEventHandler(this.OnClosing);
            this.mainTabs.ResumeLayout(false);
            this.queryPage.ResumeLayout(false);
            this.settingPage.ResumeLayout(false);
            this.queryRoot.ResumeLayout(false);
            this.topFilters.ResumeLayout(false);
            this.topFilters.PerformLayout();
            this.startDateTimePanel.ResumeLayout(false);
            this.endDateTimePanel.ResumeLayout(false);
            this.logLevelsPanel.ResumeLayout(false);
            this.logLevelsPanel.PerformLayout();
            this.queryButtonsPanel.ResumeLayout(false);
            this.queryButtonsPanel.PerformLayout();
            this.gridHost.ResumeLayout(false);
            ((ISupportInitialize)(this.grid)).EndInit();
            this.gridContextMenu.ResumeLayout(false);
            this.settingsPanel.ResumeLayout(false);
            this.settingsPanel.PerformLayout();
            this.folderButtonsPanel.ResumeLayout(false);
            this.folderButtonsPanel.PerformLayout();
            ((ISupportInitialize)(this.refreshNumber)).EndInit();
            ((ISupportInitialize)(this.maxNumber)).EndInit();
            ((ISupportInitialize)(this.cleanupNumber)).EndInit();
            this.settingsButtonsPanel.ResumeLayout(false);
            this.settingsButtonsPanel.PerformLayout();
            this.ResumeLayout(false);
        }
    }
}
